FROM easybuilders/base:centos7-eb4.2.1
# create /scratch & /easybuild directories
USER root
RUN mkdir /scratch && chown easybuild:easybuild /scratch
RUN mkdir /easybuild && chown easybuild:easybuild /easybuild
USER easybuild
# use /easybuild for everything that should persist in the container (software, modules and sources)
# everything else goes in /scratch, which will be cleaned out
ENV EASYBUILD_PREFIX=/scratch
ENV EASYBUILD_INSTALLPATH=/easybuild
ENV EASYBUILD_SOURCEPATH=/easybuild/sources
# disable output buffering in Python, so we see EasyBuild output as it progresses
ENV PYTHONUNBUFFERED=TRUE
# install software & accompanying modules
RUN eb GCC-9.3.0.eb --robot --trace \
  # clean up everything in /scratch
  && rm -rf /scratch/*
# finalize /easybuild, no changes can be made in /easybuild that persist!
VOLUME /easybuild
# make sure we start in /home/easybuild rather than / when shell in started in container
WORKDIR /home/easybuild
