FROM easybuilders/test:centos7-eb421-gcc930
# install software & accompanying modules
RUN (eb foss-2020a.eb --robot || tail -100 `eb --last-log`) \
  # clean up everything in /scratch
  && rm -rf /scratch/*
